#!/usr/bin/env bash

# check args
if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign parameters to variables
path="$1"
ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path" "$username@$ip":~/
