#!/usr/bin/env bash
# script that creates custom header
# search
apt-get -y update
apt-get -y install nginx
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME:" /etc/nginx/sites-enabled/default

# test syntax
sudo nginx -t

# restart server
sudo service nginx restart
